# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
stage: dev

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent

mfshell:
  name: mfshell
  priceimportschedule: "1 15 * * *"
  processtransactionschedule: "58 17 * * *"

pv:
  mntpath: /mnt/data/mf/
  configpvc: mfshellconfigpvc
  configstorage: _config/
  configstoragesize: 1Mi 

