# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent

mfshell:
  name: mfshell
  schedule: "1 15 * * *" 

pv:
  configpvc: mfshellconfigpvc
  configstorage: /mnt/data/mf/prod_config/
  configstoragesize: 1Mi 

