apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.configpvc }}
spec:
  storageClassName: mffeconfigstorage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.pv.configstoragesize }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mffeconfigstorage
spec:
  storageClassName: mffeconfigstorage
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: {{ .Values.pv.configstoragesize }}
  hostPath:
    path: {{ .Values.pv.configstorage }}
    type: DirectoryOrCreate 

