logging:
  level:
    root: INFO
    de.hf.myfinance: DEBUG

spring:
  main:
    web-application-type: NONE

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.processRecurrentTransaction-out-0:
    destination: processRecurrentTransaction
    producer:
      required-groups: processRecurrentTransactionAuditGroup
  bindings.loadNewMarketData-out-0:
    destination: loadNewMarketDataRequest
    producer:
      required-groups: loadNewMarketDataAuditGroup

spring.rabbitmq:
  host: 192.168.100.73
  port: 30021
  username: user
  password: vulkan

job:
  name: importMarketData
