/*
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.hf.dac.myfinance.client.api;

import io.swagger.client.ApiException;
import de.hf.dac.myfinance.client.model.BaseMFRunnerParameter;
import de.hf.dac.myfinance.client.model.JobInformation;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MyFinanceRunnerApi
 */
@Ignore
public class MyFinanceRunnerApiTest {

    private final MyFinanceRunnerApi api = new MyFinanceRunnerApi();

    
    /**
     * list known cops jobs
     *
     * List all JobInformation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        List<Object> response = api.list();

        // TODO: test validations
    }
    
    /**
     * execute myfinance launcher
     *
     * Execute myfinance Core Launcher
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startTest() throws ApiException {
        String env = null;
        String jobtype = null;
        BaseMFRunnerParameter params = null;
        JobInformation response = api.start(env, jobtype, params);

        // TODO: test validations
    }
    
    /**
     * get status of cops jobs
     *
     * JobInformation of actual Job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void statusTest() throws ApiException {
        String uuid = null;
        JobInformation response = api.status(uuid);

        // TODO: test validations
    }
    
}
